### ISSUE TITLE
K-9 Mail crashes when I try to Send

### ISSUE THREAD

**Issue by physkets** [JohnLines/mediclog#24] opened 2020-01-04 17:00 UTC
As described, when I press 'Send', and choose K-9 Mail, it attempts to open it, but it crashed without any error message.

I am using the latest stable version of both, from F-Droid.

**Comment by JohnLines** [comment] 2020-01-06 13:26
I am having problems reproducing this, using with K9-Mail both on my main phone (which could be a special case as I install directly to it via ADB, and my test phone, which is a Samsung Galaxy S3 - which is probably older than the yours as it runs Android 4.3.
On an emulator running Android 5.1.1, with Gmail I do get a crash, but gmail crashes as soon as invoked anyway on there, probably because it is not logged in to Google.

Could you let me know your Android Version ?

**Comment by physkets** [comment] 2020-01-06 14:15
I am using Android 9.0 (actually LineageOS 16.0). The crash is immediate, in that K-9 does not even appear.

**Comment by JohnLines** [comment] 2020-01-06 16:55
Under an Android 9.0 emulator I see the same results, with a message

LocalFileProvider - openFile: fileLocation: /data/user/0/org.paladyn.mediclog/files/mediclog.txtis invalid
followed by an exception in mediclog, followe by

W InputDispatcher: channel '7f72001 com.fsck.k9/com.fsck.k9.activity.MessageCompose (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

E InputDispatcher: channel '7f72001 com.fsck.k9/com.fsck.k9.activity.MessageCompose (server)' ~ Channel is unrecoverably broken and will be disposed!

I ActivityManager: Process com.fsck.k9 (pid 8350) has died: fore TOP 

I WindowManager: WIN DEATH: Window{7f72001 u0 com.fsck.k9/com.fsck.k9.activity.MessageCompose}

**Comment by physkets** [comment] 2020-01-07 10:08
The documentation for [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider) says that it is no longer maintained an to migrate to using AndroidX:  
https://developer.android.com/jetpack/androidx/migrate

**Comment by JohnLines** [comment] 2020-01-07 18:47
A workaround for this issue has been tested on an emulator running Android 9.0, as well as Android 8.1
Workaround in release v0.2.7

**Closed by JohnLines** 2020-01-07 18:47 UTC
